import os, base64, shutil
HERE = os.path.dirname(os.path.abspath(__file__))

# Write well_knockout.py
ko_b64 = 'IiIiCndlbGxfa25vY2tvdXQucHkKLS0tLS0tLS0tLS0tLS0tLQpTaW11bGF0ZXMgYSB3ZWxsIGJlY29taW5nIHVuZHJpbGxhYmxlIChkcnkgaG9sZSwgcmVndWxhdG9yeSBob2xkLCBlcXVpcG1lbnQgZmFpbHVyZSkuClJlbW92ZXMgb25lIHdlbGwsIHJlLWluZGV4ZXMgdGhlIGluc3RhbmNlLCByZWJ1aWxkcyBtb2IgbWF0cml4LCByZS1ydW5zIHNvbHZlcnMuCiIiIgppbXBvcnQgY29weSwgbWF0aAoKZGVmIGJ1aWxkX2tub2Nrb3V0X2luc3RhbmNlKGJhc2VfaW5zdGFuY2UsIHdlbGxfbmFtZSk6CiAgICBpbnN0ID0gY29weS5kZWVwY29weShiYXNlX2luc3RhbmNlKQogICAgcmVtYWluaW5nID0gW3cgZm9yIHcgaW4gaW5zdFsid2VsbHMiXSBpZiB3WyJuYW1lIl0gIT0gd2VsbF9uYW1lXQogICAgaWYgbGVuKHJlbWFpbmluZykgPT0gbGVuKGluc3RbIndlbGxzIl0pOgogICAgICAgIHJhaXNlIFZhbHVlRXJyb3IoIldlbGwgJ3t9JyBub3QgZm91bmQuIi5mb3JtYXQod2VsbF9uYW1lKSkKICAgIG4gPSBsZW4ocmVtYWluaW5nKQogICAgbmFtZXMgPSB7d1sibmFtZSJdOiBpZHggZm9yIGlkeCwgdyBpbiBlbnVtZXJhdGUoaW5zdFsid2VsbHMiXSl9CiAgICBmb3IgaSwgdyBpbiBlbnVtZXJhdGUocmVtYWluaW5nKToKICAgICAgICB3WyJpZCJdID0gaQogICAgbW9iID0gW1swXSpuIGZvciBfIGluIHJhbmdlKG4pXQogICAgZm9yIGksIHdpIGluIGVudW1lcmF0ZShyZW1haW5pbmcpOgogICAgICAgIGZvciBqLCB3aiBpbiBlbnVtZXJhdGUocmVtYWluaW5nKToKICAgICAgICAgICAgaWYgaSA9PSBqOiBjb250aW51ZQogICAgICAgICAgICBpZiAidXRtX3giIGluIHdpIGFuZCAidXRtX3giIGluIHdqOgogICAgICAgICAgICAgICAgZHggPSB3aVsidXRtX3giXSAtIHdqWyJ1dG1feCJdCiAgICAgICAgICAgICAgICBkeSA9IHdpWyJ1dG1feSJdIC0gd2pbInV0bV95Il0KICAgICAgICAgICAgICAgIGRpc3Rfa20gPSBtYXRoLnNxcnQoZHgqZHggKyBkeSpkeSkgLyAxMDAwLjAKICAgICAgICAgICAgICAgIG1vYltpXVtqXSA9IG1heCgxLCBtYXRoLmNlaWwoZGlzdF9rbSAvIDUuMCkpCiAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAgICBvaSA9IG5hbWVzW3dpWyJuYW1lIl1dOyBvaiA9IG5hbWVzW3dqWyJuYW1lIl1dCiAgICAgICAgICAgICAgICBtb2JbaV1bal0gPSBiYXNlX2luc3RhbmNlWyJtb2JfdGltZSJdW29pXVtval0KICAgIGluc3RbIndlbGxzIl0gPSByZW1haW5pbmc7IGluc3RbIm5fd2VsbHMiXSA9IG4KICAgIGluc3RbIm1vYl90aW1lIl0gPSBtb2I7IGluc3RbImtub2NrZWRfb3V0Il0gPSB3ZWxsX25hbWUKICAgIHJldHVybiBpbnN0CgpkZWYgc2VsZWN0X2tub2Nrb3V0X3dlbGxzKGJhc2VfaW5zdGFuY2UsIG9wdGltYWxfc2NoZWR1bGU9Tm9uZSk6CiAgICB3ZWxscyA9IGJhc2VfaW5zdGFuY2VbIndlbGxzIl07IHNlZW4gPSBzZXQoKTsgY2FuZGlkYXRlcyA9IFtdCiAgICB0b3AgPSBtYXgod2VsbHMsIGtleT1sYW1iZGEgdzogd1siZmxvd19yYXRlIl0pCiAgICBjYW5kaWRhdGVzLmFwcGVuZCh7Im5hbWUiOiB0b3BbIm5hbWUiXSwKICAgICAgICAicmVhc29uIjogImhpZ2hlc3QgRFNUIHJhdGUgKHs6LH0gYmJsL2RheSkiLmZvcm1hdCh0b3BbImZsb3dfcmF0ZSJdKX0pCiAgICBzZWVuLmFkZCh0b3BbIm5hbWUiXSkKICAgIGlmIG9wdGltYWxfc2NoZWR1bGU6CiAgICAgICAgZmlyc3QgPSBtaW4ob3B0aW1hbF9zY2hlZHVsZSwga2V5PWxhbWJkYSBzOiBzWyJzdGFydCJdKQogICAgICAgIGlmIGZpcnN0WyJ3ZWxsX25hbWUiXSBub3QgaW4gc2VlbjoKICAgICAgICAgICAgY2FuZGlkYXRlcy5hcHBlbmQoeyJuYW1lIjogZmlyc3RbIndlbGxfbmFtZSJdLAogICAgICAgICAgICAgICAgInJlYXNvbiI6ICJmaXJzdCBkcmlsbGVkIGluIG9wdGltYWwgc2NoZWR1bGUgKGRheSB7Oi4wZn0pIi5mb3JtYXQoZmlyc3RbInN0YXJ0Il0pfSkKICAgICAgICAgICAgc2Vlbi5hZGQoZmlyc3RbIndlbGxfbmFtZSJdKQogICAgdG9wX2Jsb2NrID0gdG9wWyJuYW1lIl1bOjRdCiAgICBvdGhlciA9ICIzNC8xMCIgaWYgIjM0LzciIGluIHRvcF9ibG9jayBlbHNlICIzNC83IgogICAgb3RoZXJzID0gW3cgZm9yIHcgaW4gd2VsbHMgaWYgd1sibmFtZSJdLnN0YXJ0c3dpdGgob3RoZXIpIGFuZCB3WyJuYW1lIl0gbm90IGluIHNlZW5dCiAgICBpZiBvdGhlcnM6CiAgICAgICAgYmVzdCA9IG1heChvdGhlcnMsIGtleT1sYW1iZGEgdzogd1siZmxvd19yYXRlIl0pCiAgICAgICAgY2FuZGlkYXRlcy5hcHBlbmQoeyJuYW1lIjogYmVzdFsibmFtZSJdLAogICAgICAgICAgICAicmVhc29uIjogInRvcCB3ZWxsIGluIHt9ICh7Oix9IGJibC9kYXkpIi5mb3JtYXQob3RoZXIsIGJlc3RbImZsb3dfcmF0ZSJdKX0pCiAgICByZXR1cm4gY2FuZGlkYXRlcwoKZGVmIHN1bW1hcmlzZV9rbm9ja291dCh3ZWxsX25hbWUsIHJlYXNvbiwgYmFzZV9leGFjdCwga29fZXhhY3QsIGJhc2VfZ2EsIGtvX2dhLCBvaWxfcHJpY2UpOgogICAgZGVmIGJlc3QocCwgayk6IHJldHVybiBtaW4ocCwga2V5PWxhbWJkYSB4OiB4W2tdKSBpZiBwIGVsc2UgTm9uZQogICAgYl9tcz1iZXN0KGJhc2VfZXhhY3QsIm1ha2VzcGFuIik7IGtfbXM9YmVzdChrb19leGFjdCwibWFrZXNwYW4iKQogICAgYl9kZWY9YmVzdChiYXNlX2V4YWN0LCJkZWZlcnJlZF9wcm9kdWN0aW9uIik7IGtfZGVmPWJlc3Qoa29fZXhhY3QsImRlZmVycmVkX3Byb2R1Y3Rpb24iKQogICAgcHJpbnQoIlxuICBLTk9DS09VVDoge30gKHt9KSIuZm9ybWF0KHdlbGxfbmFtZSwgcmVhc29uKSkKICAgIHByaW50KCIgICIgKyAiLSIqNTIpCiAgICBmb3IgbGFiZWwsIGJ2LCBrdiBpbiBbCiAgICAgICAgKCJCZXN0IG1ha2VzcGFuIChkYXlzKSIsCiAgICAgICAgIHN0cihiX21zWyJtYWtlc3BhbiJdKSBpZiBiX21zIGVsc2UgIi0tIiwKICAgICAgICAgc3RyKGtfbXNbIm1ha2VzcGFuIl0pIGlmIGtfbXMgZWxzZSAiLS0iKSwKICAgICAgICAoIk1pbiBkZWZlcnJlZCBjb3N0IiwKICAgICAgICAgIiR7Oi4wZn1NIi5mb3JtYXQoYl9kZWZbImRlZmVycmVkX3Byb2R1Y3Rpb24iXSpvaWxfcHJpY2UvMWU2KSBpZiBiX2RlZiBlbHNlICItLSIsCiAgICAgICAgICIkezouMGZ9TSIuZm9ybWF0KGtfZGVmWyJkZWZlcnJlZF9wcm9kdWN0aW9uIl0qb2lsX3ByaWNlLzFlNikgaWYga19kZWYgZWxzZSAiLS0iKSwKICAgIF06CiAgICAgICAgcHJpbnQoIiAgezozMHN9ICB7Oj4xMHN9ICB7Oj4xMHN9Ii5mb3JtYXQobGFiZWwsIGJ2LCBrdikpCiAgICBkZWx0YV9tcyAgPSAoa19tc1sibWFrZXNwYW4iXSAtIGJfbXNbIm1ha2VzcGFuIl0pIGlmIGJfbXMgYW5kIGtfbXMgZWxzZSBOb25lCiAgICBkZWx0YV9kZWYgPSAoKGtfZGVmWyJkZWZlcnJlZF9wcm9kdWN0aW9uIl0gLSBiX2RlZlsiZGVmZXJyZWRfcHJvZHVjdGlvbiJdKSpvaWxfcHJpY2UvMWU2KSBpZiBiX2RlZiBhbmQga19kZWYgZWxzZSBOb25lCiAgICBpZiBkZWx0YV9tcyAgaXMgbm90IE5vbmU6IHByaW50KCIgIHs6MzBzfSAgezo+KzEwLjBmfSAgZGF5cyIuZm9ybWF0KCJNYWtlc3BhbiBjaGFuZ2UiLCBkZWx0YV9tcykpCiAgICBpZiBkZWx0YV9kZWYgaXMgbm90IE5vbmU6IHByaW50KCIgIHs6MzBzfSAgezo+KzEwLjFmfSAgJE0iLmZvcm1hdCgiRGVmZXJyZWQgY29zdCBjaGFuZ2UiLCBkZWx0YV9kZWYpKQogICAgcmV0dXJuIHsid2VsbCI6IHdlbGxfbmFtZSwgInJlYXNvbiI6IHJlYXNvbiwKICAgICAgICAgICAgImJhc2VfbWFrZXNwYW4iOiBiX21zWyJtYWtlc3BhbiJdIGlmIGJfbXMgZWxzZSBOb25lLAogICAgICAgICAgICAia29fbWFrZXNwYW4iOiAgIGtfbXNbIm1ha2VzcGFuIl0gaWYga19tcyBlbHNlIE5vbmUsCiAgICAgICAgICAgICJkZWx0YV9tYWtlc3BhbiI6IGRlbHRhX21zLAogICAgICAgICAgICAiYmFzZV9kZWZlcnJlZF91c2QiOiBiX2RlZlsiZGVmZXJyZWRfcHJvZHVjdGlvbiJdKm9pbF9wcmljZSBpZiBiX2RlZiBlbHNlIE5vbmUsCiAgICAgICAgICAgICJrb19kZWZlcnJlZF91c2QiOiAgIGtfZGVmWyJkZWZlcnJlZF9wcm9kdWN0aW9uIl0qb2lsX3ByaWNlIGlmIGtfZGVmIGVsc2UgTm9uZSwKICAgICAgICAgICAgImRlbHRhX2RlZmVycmVkX3VzZCI6IGRlbHRhX2RlZioxZTYgaWYgZGVsdGFfZGVmIGVsc2UgTm9uZSwKICAgICAgICAgICAgImtvX2V4YWN0X3BhcmV0byI6IGtvX2V4YWN0LCAia29fZ2FfcGFyZXRvIjoga29fZ2F9Cg=='
with open(os.path.join(HERE,"src","well_knockout.py"),"wb") as f:
    f.write(base64.b64decode(ko_b64))
print("  wrote src/well_knockout.py")

# Append plot_knockout_comparison to well_visualizer.py
plot_b64 = 'CgpkZWYgcGxvdF9rbm9ja291dF9jb21wYXJpc29uKGJhc2VfZXhhY3QsIGtvX3Jlc3VsdHNfbGlzdCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgb3V0cHV0X3BhdGg9ImltYWdlcy9wYXJldG9fa25vY2tvdXQucG5nIiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgb2lsX3ByaWNlPTgwLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICBjYW1wYWlnbl9sYWJlbD0iQmxvY2sgMzQgRXhwbG9yYXRpb24gQ2FtcGFpZ24iKToKICAgIGltcG9ydCBvcywgbWF0cGxvdGxpYgogICAgbWF0cGxvdGxpYi51c2UoIkFnZyIpCiAgICBpbXBvcnQgbWF0cGxvdGxpYi5weXBsb3QgYXMgcGx0CiAgICBpbXBvcnQgbWF0cGxvdGxpYi5wYXRjaGVzIGFzIG1wYXRjaGVzCiAgICBmaWcsYXg9cGx0LnN1YnBsb3RzKGZpZ3NpemU9KDExLDYpKQogICAgYmFzZV9wdHM9c29ydGVkKFsocFsibWFrZXNwYW4iXSxwWyJkZWZlcnJlZF9wcm9kdWN0aW9uIl0qb2lsX3ByaWNlKSBmb3IgcCBpbiBiYXNlX2V4YWN0XSxrZXk9bGFtYmRhIHA6cFswXSkKICAgIGJweCxicHk9emlwKCpiYXNlX3B0cykKICAgIGF4LnBsb3QoYnB4LGJweSxjb2xvcj0ic3RlZWxibHVlIixsaW5lc3R5bGU9Ii0tIixsaW5ld2lkdGg9Mix6b3JkZXI9NCkKICAgIGF4LnNjYXR0ZXIoYnB4LGJweSxjb2xvcj0ic3RlZWxibHVlIixzPTkwLGZhY2Vjb2xvcnM9Im5vbmUiLGVkZ2Vjb2xvcnM9InN0ZWVsYmx1ZSIsbGluZXdpZHRocz0yLHpvcmRlcj01KQogICAga29fY29sb3JzPVsiI2Q2MjcyOCIsIiNmZjdmMGUiLCIjOTQ2N2JkIl0KICAgIGhhbmRsZXM9W21wYXRjaGVzLlBhdGNoKGZhY2Vjb2xvcj0ibm9uZSIsZWRnZWNvbG9yPSJzdGVlbGJsdWUiLGxpbmV3aWR0aD0yLGxhYmVsPSJCYXNlbGluZSAoMjAgd2VsbHMpIildCiAgICBmb3IgaSxrbyBpbiBlbnVtZXJhdGUoa29fcmVzdWx0c19saXN0KToKICAgICAgICBpZiBub3Qga29bImtvX2V4YWN0X3BhcmV0byJdOiBjb250aW51ZQogICAgICAgIGM9a29fY29sb3JzW2klbGVuKGtvX2NvbG9ycyldCiAgICAgICAgcHRzPXNvcnRlZChbKHBbIm1ha2VzcGFuIl0scFsiZGVmZXJyZWRfcHJvZHVjdGlvbiJdKm9pbF9wcmljZSkgZm9yIHAgaW4ga29bImtvX2V4YWN0X3BhcmV0byJdXSxrZXk9bGFtYmRhIHA6cFswXSkKICAgICAgICBrcHgsa3B5PXppcCgqcHRzKQogICAgICAgIGF4LnBsb3Qoa3B4LGtweSxjb2xvcj1jLGxpbmVzdHlsZT0iLS0iLGxpbmV3aWR0aD0xLjgsem9yZGVyPTQpCiAgICAgICAgYXguc2NhdHRlcihrcHgsa3B5LGNvbG9yPWMscz04MCxmYWNlY29sb3JzPSJub25lIixlZGdlY29sb3JzPWMsbGluZXdpZHRocz0yLHpvcmRlcj01KQogICAgICAgIGRlbHRhX3N0cj0iIiBpZiBrb1siZGVsdGFfZGVmZXJyZWRfdXNkIl0gaXMgTm9uZSBlbHNlICIgKCskezouMGZ9TSBkZWZlcnJlZCkiLmZvcm1hdChrb1siZGVsdGFfZGVmZXJyZWRfdXNkIl0vMWU2KQogICAgICAgIGhhbmRsZXMuYXBwZW5kKG1wYXRjaGVzLlBhdGNoKGZhY2Vjb2xvcj0ibm9uZSIsZWRnZWNvbG9yPWMsbGluZXdpZHRoPTIsCiAgICAgICAgICAgIGxhYmVsPSJLbm9jayBvdXQge317fSIuZm9ybWF0KGtvWyJ3ZWxsIl0sZGVsdGFfc3RyKSkpCiAgICBheC5sZWdlbmQoaGFuZGxlcz1oYW5kbGVzLGxvYz0idXBwZXIgcmlnaHQiLGZyYW1lb249VHJ1ZSxmb250c2l6ZT05KQogICAgYXguc2V0X3RpdGxlKCJ7fVxuS25vY2tvdXQgU2NlbmFyaW86IFBhcmV0byBGcm9udCBDb21wYXJpc29uIi5mb3JtYXQoY2FtcGFpZ25fbGFiZWwpLGZvbnRzaXplPTEyLGZvbnR3ZWlnaHQ9ImJvbGQiLHBhZD0xMikKICAgIGF4LnNldF94bGFiZWwoIk1ha2VzcGFuIChjYW1wYWlnbiBkYXlzKSIsZm9udHNpemU9MTEpCiAgICBheC5zZXRfeWxhYmVsKCJEZWZlcnJlZCBEaXNjb3ZlcnkgVmFsdWUgKFVTRCkiLGZvbnRzaXplPTExKQogICAgYXgueWF4aXMuc2V0X21ham9yX2Zvcm1hdHRlcihwbHQuRnVuY0Zvcm1hdHRlcihsYW1iZGEgeCxfOiIkezouMGZ9TSIuZm9ybWF0KHgvMWU2KSkpCiAgICBheC5ncmlkKFRydWUsbGluZXN0eWxlPSI6IixhbHBoYT0wLjU1KTsgYXguc2V0X2ZhY2Vjb2xvcigiI2ZhZmFmYSIpCiAgICBvcy5tYWtlZGlycyhvcy5wYXRoLmRpcm5hbWUob3V0cHV0X3BhdGgpIG9yICIuIixleGlzdF9vaz1UcnVlKQogICAgcGx0LnRpZ2h0X2xheW91dCgpOyBwbHQuc2F2ZWZpZyhvdXRwdXRfcGF0aCxkcGk9MzAwLGJib3hfaW5jaGVzPSJ0aWdodCIpOyBwbHQuY2xvc2UoKQogICAgcHJpbnQoIltTVUNDRVNTXSBLbm9ja291dCBwbG90IHNhdmVkIHRvOiB7fSIuZm9ybWF0KG91dHB1dF9wYXRoKSkK'
vis_path = os.path.join(HERE,"src","well_visualizer.py")
with open(vis_path,"r",encoding="utf-8") as f: vis_src = f.read()
if "plot_knockout_comparison" not in vis_src:
    with open(vis_path,"ab") as f: f.write(base64.b64decode(plot_b64))
    print("  appended plot_knockout_comparison to well_visualizer.py")
else: print("  well_visualizer.py already has knockout plot")

# Patch main.py
mp = os.path.join(HERE,"main.py")
with open(mp,"r",encoding="utf-8") as f: src = f.read()

# Fix CSV encoding
src = src.replace("open(csv_path, 'w', newline='') as f:",
    "open(csv_path, 'w', newline='', encoding='utf-8-sig') as f:")

# Add knockout section
KO_FN = """
def run_knockout_analysis(instance, base_exact_pareto, optimal_schedule, num_steps=12, time_limit=15.0):
    from src.well_knockout import build_knockout_instance, select_knockout_wells, summarise_knockout
    print("\\n  [Knockout] selecting wells...")
    candidates = select_knockout_wells(instance, optimal_schedule)
    ko_summaries = []
    for c in candidates:
        print("\\n  Knocking out: {} ({})".format(c['name'], c['reason']))
        try: ko_inst = build_knockout_instance(instance, c['name'])
        except ValueError as e: print("  SKIP:", e); continue
        ko_exact, _, _, _ = run_exact_pareto_sweep(ko_inst, num_steps=num_steps, time_limit=time_limit)
        ko_ga, _, _ = run_ga_pareto_sweep(ko_inst, generations=150)
        summary = summarise_knockout(c['name'], c['reason'], base_exact_pareto, ko_exact, [], ko_ga, instance['oil_price'])
        ko_summaries.append(summary)
    return ko_summaries
"""
if "run_knockout_analysis" not in src:
    src = src.replace("\ndef interactive_mode", KO_FN + "\ndef interactive_mode")

KO_CALL = """
    best_sched_ko = next((p['schedule'] for p in exact_all
        if p['makespan'] == min(exact_pareto, key=lambda x: x['makespan'])['makespan']), None)
    if best_sched_ko:
        from src.well_visualizer import plot_knockout_comparison
        ko_summaries = run_knockout_analysis(instance, exact_pareto, best_sched_ko)
        if ko_summaries:
            plot_knockout_comparison(exact_pareto, ko_summaries,
                output_path=os.path.join(IMAGES_DIR, 'pareto_knockout.png'),
                oil_price=instance['oil_price'], campaign_label=CAMPAIGN_LABEL)
"""
if "plot_knockout_comparison" not in src:
    src = src.replace('    print("\\n[DONE] All outputs in output/ and images/")',
        KO_CALL + '    print("\\n[DONE] All outputs in output/ and images/")')

with open(mp,"w",encoding="utf-8") as f: f.write(src)
print("  patched main.py")

# Clear pycache
for d in ["src/__pycache__","__pycache__"]:
    full=os.path.join(HERE,d)
    if os.path.exists(full): shutil.rmtree(full)
print("\nDone! Run: python main.py")